### ISSUE TITLE
Migration fails for third_party_auth, "0007_samlconfiguration_slo_redirect_url"

### ISSUE THREAD

**Issue by johnbaldwin** [appsembler/edx-platform#233]
The third_party_auth migration, `0007_samlconfiguration_slo_redirect_url` fails when upgrading Ficus to Ginkgo because the field already exists.

One workaround is to fake this migration,

```
./manage.py lms migrate third_party_auth 0007_samlconfiguration_slo_redirect_url --fake
```

Then run the migrations as usual

**Comment by OmarIthawi** [comment]
Thanks @johnbaldwin for reporting this. I think this is no longer an issue. So I'm closing it. Re-open if that's not correct.
