### ISSUE TITLE
third_party_auth migrations fail on upgrade to Ginkgo

### ISSUE THREAD

**Issue by johnbaldwin** [appsembler/edx-platform#235]
The migration, https://github.com/appsembler/edx-platform/blob/appsembler/ginkgo/develop/common/djangoapps/third_party_auth/migrations/0007_samlconfiguration_slo_redirect_url.py, adds the 'slo_redirect_url ' field that already exists in the data imported from the Ficus instance.

Workaround is to 

```
./manage.py lms migrate third_party_auth 0007_samlconfiguration_slo_redirect_url --fake --settings=<aws|devstack_appsembler>
```

**Comment by OmarIthawi** [comment]
Thanks @johnbaldwin for reporting this. I think this is no longer an issue. So I'm closing it. Re-open if that's not correct.
