### ISSUE TITLE
Old Intercom Integration

### ISSUE THREAD

**Issue by tkeemon** [appsembler/edx-platform#24]
@natea @bezidejni @bryanlandia @annatpt @emrob (and anybody else I forgot to include) - 
Does anybody know if we're still using our Intercom integration with Open edX? 
https://github.com/appsembler/edx-platform/tree/appsembler/master/common/djangoapps/appsembler

There was a bit of refactoring on the edx-platform side of things that broke our Intercom functionality in Dogwood. I'm wondering how important that functionality is and whether or not we still use it. I know for a while our testdrives would use the chat widget to start a conversation with potential customers/leads. Is that still the case?

**Comment by bryanlandia** [comment]
TJ - Intercom may have been a better approach for announcing InterSystems container outages back when Brian and Morgan were moving to a new infrastructure.
edx-notifications didn’t provide what I wanted there.  But maybe we work to preserve the functionality if/when we need it again.

**Comment by natea** [comment]
@tkeemon we have been using Intercom in our test drives, and I'd like to use either Intercom or Helpscout Beacon to provide a feedback option for users (most likely just staff, not students). Helpscout's Beacon is more like a helpdesk, with a search of the docs right within the widget. That could reduce our customer support requests significantly, if people actually used it.

**Comment by tkeemon** [comment]
Thanks for the insights. It looks like this commit fixes the integration: 

https://github.com/appsembler/edx-platform/commit/21c578d3108da0e60110778d1d83dfcec4c4847d
