### ISSUE TITLE
Tech Debt: USE_S3_FOR_CUSTOMER_THEMES is hardcoded and should be configurable

### ISSUE THREAD

**Issue by OmarIthawi** [appsembler/edx-platform#341]
`USE_S3_FOR_CUSTOMER_THEMES` is somewhat a very bad method of choosing a storage class. 

In devstack it is mixed with `static` files, while it should be a `media` file.

The proper solution for doing such operation is to use a configurable storage class:

```
# production
CUSTOMER_THEMES_STORAGE_CLASS = 'storages.backends.s3boto.S3BotoStorage'
CUSTOMER_THEMES_STORAGE_PARAMS = {
  'location': 'customer_themes',
}

# dev
CUSTOMER_THEMES_STORAGE_CLASS = 'django.core.files.storage.FileSystemStorage'
CUSTOMER_THEMES_STORAGE_PARAMS = {}
```

This way it's fully configurable and the code won't care where it's running.

Also, this needs a cash busting mechanism. So perhaps at save, the css file should be suffixed with some GUID:

`appsembler-the-red.staging-tahoe-hawthorn.appsembler.com.e044f8e7-e4bd-44b2-9c46-6af817b1ebbd.css`

Deleting all `appsembler-the-red.staging-tahoe-hawthorn.appsembler.com.*` files before that wouldn't be a bad idea.

**Comment by abeals** [comment]
I know @OmarIthawi also tagged you on his PR, but @grozdanowski making sure you also saw this related issue to share the full rationale behind the change.

**Comment by OmarIthawi** [comment]
Thanks @abeals for having :eyes: here!
