### ISSUE TITLE
grades download reports from S3 getting bad links

### ISSUE THREAD

**Issue by bryanlandia** [appsembler/edx-platform#38]
Test Drive user reported not being able to download CSV grade reports from 
http://lms.edxdemo.appsembler.com/courses/course-v1:TheSoftwareGuild+SG101+2016_Summer/instructor#view-data_download

and I can confirm.  Links are like:
- `file:///tmp/edx-s3/grades/course-v1%253ATheSoftwareGuild%252BSG101%252B2016_Summer/TheSoftwareGuild_SG101_2016_Summer_problem_grade_report_2016-09-06-1816.csv`
- `file:///tmp/edx-s3/grades/course-v1%253ATheSoftwareGuild%252BSG101%252B2016_Summer/TheSoftwareGuild_SG101_2016_Summer_grade_report_2016-09-06-1815.csv`

On prod AMC in django shell, I did:

``` python
from django.conf import settings
settings.GRADES_DOWNLOAD
{u'STORAGE_TYPE': u'S3', u'ROOT_PATH': u'grades', u'BUCKET': u'edx-amcalpha-grade-bucket'}
```

Not sure why the method on the S3ReportStore for returning links is returning `file:///` links but it is.  Configuration looks correct.

https://github.com/appsembler/edx-platform/blob/appsembler/amc/testdrive/lms/djangoapps/instructor_task/models.py#L316

**Comment by bryanlandia** [comment]
I'm not positive this is specific only to the `appsembler/amc/testdrive` branch.

**Comment by bezidejni** [comment]
@bryanlandia That's not the Testdrive server, that's Dogwood Demo Server. The config for that is here: https://github.com/noderabbit-team/edx-configs/blob/master/dogwood_demo/production/files/server-vars.yml

**Comment by natea** [comment]
@bryanlandia @bezidejni on a demo with a prospect today, this bug reared its ugly head. Can we get this fixed on both the Dogwood Demo server and the Appsembler Academy site, so that we can properly demo the grade download feature?

**Comment by tkeemon** [comment]
Closing because I don't think any of those servers are in use anymore.
