### ISSUE TITLE
possible problem with prefixing for customer_specific assets

### ISSUE THREAD

**Issue by bryanlandia** [appsembler/edx-platform#96]
I might be missing something, but ...

https://github.com/appsembler/edx-platform/blob/appsembler/eucalyptus/master/openedx/core/djangoapps/theming/finders.py#L50

looks wrong to me.  Shouldn't it append `/customer_specific`?  My customer specific JS files are not being copied to `staticfiles`; instead, the base edx-platform ones are.

See https://github.com/appsembler/edx-theme-customers/blob/eucalyptus/trinity/lms/static/js/student_account/views/account_settings_fields.js

This is output from the `collectstatic` handler
```
(Pdb) path
u'js/student_account/views/account_settings_fields.js'
(Pdb) l
 94  	            handler = self.copy_file
 95  	
 96  	        found_files = OrderedDict()
 97  	        for finder in get_finders():
 98  	            import pdb;pdb.set_trace()
 99  ->	            for path, storage in finder.list(self.ignore_patterns):
100  	                # Prefix the relative path if the source storage contains it
101  	                if getattr(storage, 'prefix', None):
102  	                    prefixed_path = os.path.join(storage.prefix, path)
103  	                else:
104  	                    prefixed_path = path
(Pdb) n
> /edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py(101)collect()
-> if getattr(storage, 'prefix', None):
(Pdb) 
> /edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py(102)collect()
-> prefixed_path = os.path.join(storage.prefix, path)
(Pdb) 
> /edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py(106)collect()
-> if prefixed_path not in found_files:
(Pdb) 
> /edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py(107)collect()
-> found_files[prefixed_path] = (storage, path)
(Pdb) 
> /edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py(108)collect()
-> handler(path, prefixed_path, storage)
(Pdb) s
--Call--
> /edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py(298)copy_file()
-> def copy_file(self, path, prefixed_path, source_storage):
(Pdb) a
self = <django.contrib.staticfiles.management.commands.collectstatic.Command object at 0x7f3f580eea90>
path = js/student_account/views/account_settings_view.js
prefixed_path = eucalyptus-theme-codebase/js/student_account/views/account_settings_view.js
source_storage = <openedx.core.djangoapps.theming.storage.ThemeStorage object at 0x7f3f4b34c950>
(Pdb) 
```

I'm trying to collect static assets from the Trinity Euc. customer specific theme, and the prefixed path is missing `customer_specific`.

**Comment by bryanlandia** [comment]
If I change  in `openedx/core/djangoapps/theming/finders.py#L48-51`

```
            customer_theme_storage = self.storage_class(
                os.path.join(theme.customer_specific_path, self.source_dir),
                prefix=theme.theme_dir_name,
            )
```

to 

```
            customer_theme_storage = self.storage_class(
                os.path.join(theme.customer_specific_path, self.source_dir),
                prefix=os.path.join(theme.theme_dir_name, 'customer_specific'),
            )
```

then `collectstatic` does copy the assets from the `customer_specific/...` folder, but then they get copied over by the same assets in `edx-platform`.  

```
Copying '/edx/var/edxapp/themes/eucalyptus-theme-codebase/customer_specific/lms/static/sass/_customer-specific.scss'
Copying '/edx/var/edxapp/themes/eucalyptus-theme-codebase/customer_specific/lms/static/sass/base/_branding-basics.scss'
Copying '/edx/var/edxapp/themes/eucalyptus-theme-codebase/customer_specific/lms/static/js/student_account/views/RegisterView.js'
Copying '/edx/var/edxapp/themes/eucalyptus-theme-codebase/customer_specific/lms/static/js/student_account/views/account_settings_fields.js'
Copying '/edx/var/edxapp/themes/eucalyptus-theme-codebase/customer_specific/lms/static/js/student_account/views/account_settings_view.js'
Copying '/edx/var/edxapp/themes/eucalyptus-theme-codebase/customer_specific/lms/static/js/student_account/views/account_settings_factory.js'
Copying '/edx/var/edxapp/themes/eucalyptus-theme-codebase/customer_specific/lms/static/js/student_account/models/trinity_user_profile_model.js'
Copying '/edx/var/edxapp/themes/eucalyptus-theme-codebase/customer_specific/lms/static/images/favicon.ico'
Copying '/edx/var/edxapp/themes/eucalyptus-theme-codebase/customer_specific/lms/static/images/hero.jpg'
Copying '/edx/var/edxapp/themes/eucalyptus-theme-codebase/customer_specific/lms/static/images/branding/brand-logo.png'
Copying '/edx/var/edxapp/themes/eucalyptus-theme-codebase/customer_specific/lms/static/images/branding/icon-black.png'
Copying '/edx/app/edxapp/edx-platform/lms/static/js/student_account/views/account_settings_fields.js'
Copying '/edx/app/edxapp/edx-platform/lms/static/js/student_account/views/account_settings_view.js'
Copying '/edx/app/edxapp/edx-platform/lms/static/js/student_account/views/account_settings_factory.js'
```

It should be that the first file found is kept.  The theme finder is being used first, so that is correct, but the default Open edX finder is then overwriting it.  I'm still investigating a bit more.

**Comment by bryanlandia** [comment]
OK, I was misunderstanding something here.  The staticfiles from eucalyptus-theme-codebase are not overriding what's in `/edx/var/edxapp/staticfiles/js/...` but are being copied to `/edx/var/edxapp/staticfiles/eucalyptus-theme-codebase/js/...`  and overrides have to be referenced with a url path that includes `eucalyptus-theme-codebase`, so now I have ...

```
<%static:require_module module_name="eucalyptus-theme-codebase/js/student_account/views/account_settings_factory" class_name="AccountSettingsFactory">
```

**Comment by bryanlandia** [comment]
@bezidejni Have you looked into overriding any paths that are also in edx-platform?  It works to add the prefix "eucalyptus-theme-codebase" to all the JS calls, but it ends up sometimes being a lot of files you have to override to make a change in just one file.

**Comment by bezidejni** [comment]
@bryanlandia Hey Bryan, you're correct, the assets from the `customer_specific` dir should end up in the `THEME_NAME` dir and override the assets from the theme codebase. The reason it was done that was it because that's what edx does by defaults, copies the assets inside a theme folder instead of directly overriding the assets from edx-platform.

I haven't really given much thought about overriding paths from edx-platform simply because it wasn't needed for our case. For referencing overrides in the theme, have you tried prepending a slash to the file path instead of adding the theme name there? I know that works for the templates, don't know if it will for static files as well. For AMC, we really didn't have the need to override static files from edx-platform, so we didn't do much testing of that unfortunately. Ideally, I agree that you shouldn't need to add the theme name to the static include in order to load the file from the theme or customer override. If prepending the slash doesn't work and you have an idea that we can use, I'm all ears.

**Comment by bryanlandia** [comment]
Thanks @bezidejni - Makes sense.  I haven't tried prepending a slash--that would still mean I have to change just as many files anyhow.  I might dig into whether there's something clever we can do with Require.js defines and static includes to look first inside the theme URL path and fall back to the normal path.
